#include <iostream>
using namespace std;
int main()
{
    float num01 , num02;
    cout<<"Enter two number : ";
    cin>>num01>>num02;
    cout<<"Numbers are == or not "<<(num01==num02)<<endl;
    cout<<"Number are <= or not "<<(num01<=num02)<<endl;
    cout<<"Number are >= or not "<<(num01>=num02)<<endl;
    cout<<"Number are > or not "<<(num01>num02)<<endl;
    cout<<"Number are < or not "<<(num01<num02);
}