#include<iostream>
using namespace std;
int main()
{
    int num01;
    cout<<"Enter a number :";
    cin>>num01;
    float num02;
    cout<<"Enter a number in decimal :";
    cin>>num02;
    string name;
    cout<<"Enter a your name :";
    cin>>name;
    bool letter;
    cout<<"Enter a buoolion :";
    cin>>letter;
    cout<<"you enter a "<<num01<<endl;
    cout<<"You enter a "<<num02<<endl;
    cout<<"you enter a "<<name<<endl;
    cout<<"you enter a "<<letter<<endl;
   

}